#!/usr/bin/env python

import sys
import urllib2
import codecs, sys

try:
	import json
except ImportError:
	import simplejson as json

API_KEY = "f082a2783c9881e0edfd4c9247d1828b"
RESOLVE_URL = "http://api.soundcloud.com/resolve.json?url=%(sc_url)s&client_id=%(key)s"
RGP_SET_URLS = [
	'http://soundcloud.com/radio-gladys-palmera/sets/las-sesiones-de-gladys',
	'http://soundcloud.com/radio-gladys-palmera/sets/latin-vintage-1'
]

OPML_START = """<?xml version="1.0" encoding="UTF-8"?>
<!-- OPML generated by soundcloud-opml -->
<opml version="1.1">
	<head>
		<title>Squeezebox Faves</title>
	</head>
	<body>
		<outline text="Faves on MySqueezebox.com" title="Faves on MySqueezebox.com">"""
OPML_END = """		</outline>
	</body>
</opml>"""

OPML_SET_OUTLINE_FEED = '<outline text="%(set_title)s">'

OPML_END_OUTLINE_FEED = '</outline>'

OPML_TRACK_OUTLINE_FEED = '<outline text="%(title)s" title="%(title)s" type="audio" icon="%(artwork_url)s" URL="%(stream_url)s" />'

def get_set(url):
	# You'll be better able to see what's happening if you turn on debugging
	h=urllib2.HTTPHandler(debuglevel=0)
	request = urllib2.Request(url)
	opener = urllib2.build_opener(h)
	data = opener.open(request).read()
	return json.loads(data)	

def main():
	print OPML_START

	for set_url in RGP_SET_URLS:
		s_set = get_set(RESOLVE_URL % {'sc_url': set_url, 'key': API_KEY})
		s_set_title = s_set['title'].replace('"', '&quot;')
		s_set_tracks = s_set['tracks']

		print OPML_SET_OUTLINE_FEED % {'set_title': s_set_title} 

		for s_track in s_set_tracks:
			s_track_title = s_track['title'].replace('"', '&quot;')
			s_track_artwork_url = s_track['artwork_url']
			s_track_stream_url = s_track['stream_url']

			print OPML_TRACK_OUTLINE_FEED % {'title': s_track_title, 'artwork_url': s_track_artwork_url, 'stream_url': s_track_stream_url}

		print OPML_END_OUTLINE_FEED

	print OPML_END

if __name__ == "__main__":
	# By default, the stdout stream in python is assumed 
	# to have ascii encoding. 
	# This aims to get stdout to a non-ascii encoding
	sys.stdout = codecs.getwriter('utf8')(sys.stdout)
	main()
